feat(drash/v2.x): services end and startup
drashland/website-v2 pull request #124
Opened 2022-04-03 22:59 UTC by crookse

* Improves services docs
* Adds docs for `service.end()` and `service.runAtStartup()`
* Adds docs showing how to create services of different types using the different methods:
  * `runAtStartup()`
  * `runBeforeResource()`
  * `runAfterResource()`
* Organizes services tutorials in side bar

2022-04-08 16:12 UTC, ebebbington requested changes
Everything else looks good :)

2022-04-08 16:12 UTC, ebebbington commented on docs/drash/v2.x/2_tutorials/6_services/3_creating_services/3_server_level/3_running_before_resources.md
> +     hostname: "0.0.0.0",
applies to all areas that use `0.0.0.0` - we should use localhost, because that will be cross-platform, whereas i think 0.0.0.0 is MacOS specific (and linux maybe?)

2022-04-08 16:12 UTC, ebebbington commented on docs/drash/v2.x/2_tutorials/6_services/3_creating_services/3_server_level/3_running_before_resources.md
> +     hostname: "0.0.0.0",
so if a windows user comes along, this just wont work for them, especially if they're beginners and dont realise they can just replace it with localhost or 127

2022-04-08 16:23 UTC, crookse commented on docs/drash/v2.x/2_tutorials/6_services/3_creating_services/3_server_level/3_running_before_resources.md
> +     hostname: "0.0.0.0",
i see. i thought it was 0.0.0.0 that was cross compatible because we had localhost in max, ubuntu, and windows tests and changed to 0.0.0.0 to make them pass. anyways, ill get those changes in.

also, i need to fix the docs based on what we agree on for request.end() in https://github.com/drashland/drash/pull/625

2022-05-10 02:25 UTC, crookse commented on docs/drash/v2.x/2_tutorials/6_services/3_creating_services/3_server_level/3_running_before_resources.md
> +     hostname: "0.0.0.0",
made the change: [3b5663c](https://github.com/drashland/website-v2/pull/124/commits/3b5663c588e6533f2a7406aebc92431e8ccc157c)

2022-05-10 02:25 UTC, crookse commented
PR is ready for review again. I updated the Drash Lifecycle Diagram as well to state `request.end()` and not `this.end()` for the services flows

2022-05-10 06:32 UTC, ebebbington approved these changes

2022-05-15 01:27 UTC, merged